theme: jekyll-theme-minimal
title: AI & ML Consulting
description: "AI/ML consultancy for scalable data science, MLOps, and applied machine learning, specialising in AWS, Kubernetes, and agentic AI."
author: "Emma Ai"

# SEO & social plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
